handle:
- rewrite: if(path=="/tinywebdb")goto "/php/tinywebdb.php [L]"
- rewrite: if(path=="/tinywebdb/")goto "/php/tinywebdb.php [L]"
- rewrite: if(path=="/tinywebdb/manage")goto "/php/tinywebdbMANAGE.php [L]"
- rewrite: if(path=="/tinywebdb/storeavalue")goto "/php/tinywebdb.php?do=storeavalue [L]"
- rewrite: if(path=="/tinywebdb/getvalue")goto "/php/tinywebdb.php?do=getvalue [L]"
- rewrite: if(path=="/tinywebdb/file" && query_string=="filename=(.*)")goto "/php/tinywebdb.php?do=file&filename=%1 [L]"
- rewrite: if(path=="/tinywebdb/addfile" && query_string=="filename=(.*)")goto "/php/tinywebdb.php?do=addfile&filename=%1 [L]"
- rewrite: if(path=="/tinywebdb/savefile" && query_string=="filename=(.*)")goto "/php/tinywebdb.php?do=savefile&filename=%1 [L]"
- rewrite: if(path=="/tinywebdb/updatefile" && query_string=="filename=(.*)")goto "/php/tinywebdb.php?do=updatefile&filename=%1 [L]"
- rewrite: if(path=="/tinywebdb/file(.*)")goto "/php/tinywebdb.php?do=getfile&filename=$1 [L]"
- rewrite: if(path=="/tinywebdb/autobackup")goto "/php/autobackup.php [L]"

cron:
- url: /tinywebdb/autobackup
  schedule: "0 5 * * *"
  description: "每天早上 5 点执行自动备份"