<?
define('MANAGEversion','201704291');
require_once('class/db.php');

@error_reporting(E_ALL &~ E_NOTICE);
@set_time_limit(0);
date_default_timezone_set('PRC');
if(!isset($_SERVER['PHP_SELF'])||empty($_SERVER['PHP_SELF']))$_SERVER['PHP_SELF']=$_SERVER['SCRIPT_NAME'];
header('Content-type:text/html;charset=utf-8');
$password=setting::get('password');if($password==''&&$_REQUEST['a']!='init'){exit('<script>window.location.href="?a=init"</script>');}define('PWD',md5($password));
session_start();
$cookiepwd=isset($_SESSION['tinywebdbmanage'])?$_SESSION['tinywebdbmanage']:'';
$a=isset($_REQUEST['a'])?$_REQUEST['a']:'index';if(isset($_REQUEST['k']))$k=$_REQUEST['k'];if(isset($_REQUEST['v']))$v=$_REQUEST['v'];

function check_login(){global $cookiepwd;if($cookiepwd!=PWD)exit('<script>window.location.href="?a=index"</script>');}
function urlencode_plus($s){
    $s=str_replace('%','%25',$s);
    $s=str_replace('+','%2B',$s);
    $s=str_replace(' ','%20',$s);
    $s=str_replace('/','%2F',$s);
    $s=str_replace('?','%3F',$s);
    $s=str_replace('#','%23',$s);
    $s=str_replace('&','%26',$s);
    $s=str_replace('=','%3D',$s);
    return $s;
}

if($a=='login'){$passwd=md5($_POST['passwd']);if($passwd==PWD){$_SESSION['tinywebdbmanage']=$passwd;exit('<script>window.location.href="?a=all"</script>');}else exit('<script>alert("密码错误");history.go(-1);</script>');}
elseif($a=='logout'){$_SESSION['tinywebdbmanage']='';echo'<script>window.location.href="?a=index";</script>';}

if($_REQUEST['noecho']!='true'){
  ?><html><?
	?><head><title>TinyWebDB Manager</title><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"><script src="//cdn.bootcss.com/jquery/3.2.1/jquery.js"></script><link rel="stylesheet" href="/script/manage.css"><script src="/script/manage.js"></script></head><?
	?><body onload="setTimeout(CheckUpdate('aix.colintree.cn',<? echo MANAGEversion;?>),2000);setTimeout(CheckUpdate('www.source-space.cn',<? echo MANAGEversion;?>),2000);"><div id="body"><div id="header"><div id="title" class="text-center"><a href="/tinywebdb">TinyWebDB</a></div><div class="btn-group btn-group-justified"><a id="update_available" href="http://aix.colintree.cn/article/TinyWebDB_SAE_PHP-1" style="display:none;color:red;" class="btn btn-default">管理系统有更新！</a><a href="?a=all" class="btn btn-default">全部</a><a href="?a=set" class="btn btn-default">添加</a><a href="?a=backup" class="btn btn-default">备份/恢复</a><a href="?a=setting" class="btn btn-default">设置</a><a href="?a=logout" class="btn btn-default">退出</a></div></div><div id="main"><div id="all_processing_background" style="display:none"><div class="panel panel-default"><div class="panel-body text-center"><h4 id="all_processing_msg1">MSG1</h4><h4 id="all_processing_msg2" style="margin:0">MSG2</h4></div></div></div><?
}
switch($a){
	case'init': require('init.php'); break;
	case'index': if($cookiepwd==PWD)exit('<script>window.location.href="?a=all"</script>');?><div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">请输入后台密码</h3></div><div class="panel-body"><form action="?a=login" method="post"><div class="input-group"><input autocomplete="off" type="password" class="form-control" name="passwd"><span class="input-group-btn"><input class="btn btn-default" type="submit" value="确定"></span></div></form></div></div><? break;
	case'set': check_login(); if(isset($k) && isset($v)){db::set($k,$v);?><div class="alert alert-success"><h3>设置成功</h3><p>Tag:<code><? echo htmlspecialchars($k); ?></code></p><p>Value:</p><pre style="word-break:break-word"><? echo htmlspecialchars($v); ?></pre></div><?}else{$v=db::get($k);?><div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">添加/修改</h3></div><div class="panel-body text-center"><form action="?a=set" method="post"><p>Tag:<input type="text" class="form-control" name="k" value="<? echo htmlspecialchars($k); ?>"/></p><p>Value:</p><textarea rows="8" name="v" class="form-control"><? echo htmlspecialchars($v); ?></textarea><p><input type="submit" value="保存" class="btn btn-default"/></p></form></div></div><?} break;
	case'get': check_login(); if(isset($k)){$v=db::get($k);if($v!==FALSE){$view = isset($_REQUEST['view'])?$_REQUEST['view']:'';if($view=='json'&&is_string($view))$v=json_decode($v,1);?><div class="alert alert-success"><p><a href="?a=get&view=json&k=<? echo urlencode($k);?>" class="btn btn-default">Json解码</a></p><p>Key:<? echo htmlspecialchars($k); ?></p><p>Val:</p><pre><? echo htmlspecialchars(print_r($v,true)); ?></pre></div><?}else{echo '<dic class="alert alert-danger">',htmlspecialchars($k),' 不存在！</div>';}}else{?><div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">查看</h3></div><div class="panel-body text-center"><form action="?a=get" method="post"><div class="input-group"><input type="text" class="form-control" name="k"><span class="input-group-btn"><input class="btn btn-default" type="submit" value="查看"></span></div></form></div></div><?} break;
	case'del': check_login(); if(isset($k)){$v=db::del($k);?><div class="alert alert-success"><? echo htmlspecialchars($k); ?> 已删除！</div><?}else{?><div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">删除</h3></div><div class="panel-body text-center"><form action="?a=del" method="post"><div class="input-group"><input type="text" class="form-control" name="k"/><span class="input-group-btn"><input class="btn btn-default" type="submit" value="删除" /></span></div></form></div></div><?} break;
	case'backup': check_login(); require('backup.php'); break;
	case'setting': check_login(); require('setting.php'); break;
	case'all': check_login(); ?><div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title" style="display:inline-block">标签 - <? $all_category=explode('#',setting::get('all_categorylist'));if(isset($_REQUEST['category'])){array_unshift($all_category,$_REQUEST['category']);}$all_category=array_unique($all_category);if(!is_array($all_category) || empty($all_category)){$all_category=[''];} ?><select id="all_category"><? foreach($all_category as $category){echo'<option value="',htmlspecialchars($category),'">',($category==''?'显示所有':$category),'</option>';} ?></select></h3><form method="get" id="all_search_form"><div class="input-group"><input autocomplete="off" type="text" placeholder="搜索" class="form-control" name="keyword"><input type="hidden" name="a" value="search"><span class="input-group-btn"><button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button></span></div></form></div><div class="panel-body text-center"><div id="all_toolbar_frame" class="panel panel-default text-center" style="display:none">操作：<button id="all_toolbar_selectall" class="btn btn-primary">全选</button><button id="all_toolbar_selectnone" style="display:none" class="btn btn-primary">全不选</button><button id="all_toolbar_delete" class="btn btn-danger">删除</button></div><table class="table table-hover"><thead><th></th><th>标签-值</th><th>操作</th></thead><tbody><? foreach(db::getall($_REQUEST['category']) as $k=>$v){$showTag=htmlspecialchars($k);$showValue=substr(str_replace("\n",'',htmlspecialchars($v)),0,120);echo'<tr>', '<td><input type="checkbox" tinywebdb_key="',$showTag,'"></td>', '<td>',$showTag,'<br><div class="tinywebdb-value">',$showValue,'</div></td>', '<td><a href="?a=get&k=',urlencode_plus($k),'" class="btn btn-primary" button-task="show-tag">查看</a><a href="?a=set&k=',urlencode_plus($k),'" class="btn btn-primary" button-task="edit-tag">修改</a><a href="?a=del&k=',urlencode_plus($k),'" onclick="return confirm(\'确认删除？\');" class="btn btn-danger" button-task="delete-tag">删除</a></td>', '</tr>';}?></tbody></table></div></div><? break;
    case'search': check_login(); ?><form method="get" id="search_form"><div class="input-group"><input autocomplete="off" type="text" class="form-control" name="keyword" value="<? echo htmlspecialchars($_GET['keyword']); ?>"><input type="hidden" name="a" value="search"><span class="input-group-btn"><input class="btn btn-default" type="submit" value="搜索"></span></div><div class="panel panel-default"><div class="panel-heading"><div id="search_filter_controler"><b>搜索条件</b><span></span></div><div><div class="checkbox"><label><input type="checkbox" name="ignorecase"<? echo($_GET['ignorecase']=='on'?' checked':'');?>>忽略大小写</label></div><label class="radio-inline"><input type="radio" name="range" value="tag"<? echo($_GET['range']!='value'&&$_GET['range']!='both'?' checked':'');?>>标签</label><label class="radio-inline"><input type="radio" name="range" value="value"<? echo($_GET['range']=='value'?' checked':'');?>>值</label><label class="radio-inline"><input type="radio" name="range" value="both"<? echo($_GET['range']=='both'?' checked':'');?>>标签或值</label></div></div></div></form><? $search_rst=$_GET['keyword']=='' ? db::getall() : db::search($_GET['keyword'],$_GET['ignorecase']=='on',$_GET['range']!='value',$_GET['range']=='value'||$_GET['range']=='both'); ?><div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">搜索结果<? if(!empty($search_rst)){echo' 找到',count($search_rst)+0,'条结果';} ?></h3></div><div class="panel-body text-center"><div id="all_toolbar_frame" class="panel panel-default text-center" style="display:none">操作：<button id="all_toolbar_selectall" class="btn btn-primary">全选</button><button id="all_toolbar_selectnone" style="display:none" class="btn btn-primary">全不选</button><button id="all_toolbar_delete" class="btn btn-danger">删除</button></div><table class="table table-hover"><? if(!empty($search_rst)){?><thead><th></th><th>标签-值</th><th>操作</th></thead><tbody><? foreach($search_rst as $k=>$v){$showTag=htmlspecialchars($k);$showValue=substr(str_replace("\n",'',htmlspecialchars($v)),0,120);echo'<tr>', '<td><input type="checkbox" tinywebdb_key="',$showTag,'"></td>', '<td>',$showTag,'<br><div class="tinywebdb-value">',$showValue,'</div></td>', '<td><a href="?a=get&k=',urlencode_plus($k),'" class="btn btn-primary" button-task="show-tag">查看</a><a href="?a=set&k=',urlencode_plus($k),'" class="btn btn-primary" button-task="edit-tag">修改</a><a href="?a=del&k=',urlencode_plus($k),'" onclick="return confirm(\'确认删除？\');" class="btn btn-danger" button-task="delete-tag">删除</a></td>', '</tr>';}?></tbody><?}else{echo'<tr><td colspan="3" class="text-center" style="border:0">没有找到 ',($_GET['range']=='both'?'标签和值':($_GET['range']=='value'?'值':'标签')),' 中包含关键字的结果</td></tr>';}?></table></div></div><? break;
    case'mdelete': check_login(); if(isset($_POST['tags'])){db::mdelete($_POST['tags']);}exit('finish'); break;
}
?><div style="width:100%;padding-left:10px;color:#bbb;">TinyWebDB MANAGE System By ColinTree @ <a target="_blank" style="color:#bbb;text-decoration:underline" href="http://www.colintree.cn">colintree.cn</a> VERSION: <? echo MANAGEversion;?></div>